name: Deploy to IONOS (Shithead)

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 📁 Create Remote Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: mkdir -p /dist/shithead/

      - name: 🚀 Deploy to IONOS via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './public/.'
          remote_path: '/dist/shithead/'
          sftp_only: true
          delete_remote_files: false
